spring:
  application:
    name: TheMarujoHyperBlog
  datasource:
    url: jdbc:mysql://localhost:3306/blogdb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: marujo
    password: marujo
  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      enabled : true
      max-file-size: 10MB
      max-request-size: 10MB
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 514051386784-i4n1leb6rjk8h5hbovtnfquhlb4o0as1.apps.googleusercontent.com
            client-secret: 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
            #scope: profile, email
            #redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            #authorization-grant-type: authorization_code
            client-authentication-method: post
          github:
            client-id: Iv23li3nWCIgsN6jc4Y4
            client-secret: 34cda707ce8f034449684c050c8e56263277f240
            #scope: profile, email
            #authorization-grant-type: authorization_code
            #client-authentication-method: post
            #provider:
            #google:
            #authorization-uri: https://accounts.google.com/o/oauth2/auth
            #token-uri: https://oauth2.googleapis.com/token
            #user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            #user-name-attribute: sub
            #github:
            #authorization-uri: https://github.com/login/oauth/authorize
            #token-uri: https://github.com/login/oauth/access_token
            #user-info-uri: https://api.github.com/user
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    enabled: true

  # Spring email configuration
  mail:
    host: smtp.gmail.com
    port: 587
    username: mausamtiwari93@gmail.com
    password: bchkcgsicerwxknr  # This is a hashed password for smtp (app password)
    properties:
       mail:
        debug: true
        smtp:
          auth: true       # specify whether the authentication should be used when connecting to the smtp server
          starttls:
            enable: true    # specify whether the starttls protocol should be used when connecting to the smtp server
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

logging:
  level:
    org.springframework: INFO
    be.intec.themarujohyperblog: DEBUG


server:
  tomcat:
    max-http-form-post-size: 10MB


management:
  health:
    mail:
      enabled: true



